umapp/urls.py
from django.urls import path
from .views import *


app_name = "umapp"
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signin/', SigninView.as_view(), name='signin'),
    path('signout/', SignoutView.as_view(), name='signout'),
    path('um-admin/', AdminHomeView.as_view(), name='admin'),
    path('um-admin/blog/create', AdminBlogCreateView.as_view(),
         name='adminblogcreate'),
    path('blog/list/', AdminBlogListView.as_view(), name='adminbloglist'),
    path('blog/<int:pk>/upd/', AdminBlogUpdateView.as_view(), name="adminblogupdate"),
    path('blog/<int:pk>/delete/',
         AdminBlogDeleteView.as_view(), name="adminblogdelete"),
    path('blog/<int:pk>/detail/', BlogDetailView.as_view(), name='blogdetail'),
    path('blog/<int:pk>/comment/', BlogCommentView.as_view(), name='blogcomment'),
    path('password-change/', PasswordChangeView.as_view(), name='passwordchange'),


]

umproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('umapp.urls', namespace='umapp')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

umapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Blog(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to="blogs")
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Comment(models.Model):
    commentor = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.commentor.username

templates/adminblogcreate.html
{% extends "base.html" %}


{% block content %}

<div class = "row">
	<div class = "cd-md-4 mx-auto">
		<h4> Add new blog</h4>
		<form method = "POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form.as_p }} 
			<button class = "btn btn-info btn-block "> Bujhaunus</button>
		</form>
		
	</div>

	
</div>

{% endblock %}

templates/adminblogdelete.html
{% extends "base.html" %}


{% block content %}

<h3>Blog Delete</h3>
<form method = "Post">
{% csrf_token %}
<p>Are you Sure To delete?</p>
<button class = "btn btn-danger">yes</button>
<a href="/post/list/" class="btn btn-info"> No</a>
</form>
 




{% endblock %}

templates/adminbloglist.html
{% extends "base.html" %}


{% block content %}

<table id="example" class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>SN</th>
			<th>Title</th>
			<th>Image</th>
			<th>Author</th>
		</tr>
	</thead>
	<tbody>
		{% for blog in allblogs %}
		<tr>
			<td>{{forloop.counter}}</td>

			<td><a href="">{{blog.tilte}}</a></td>
			<td>{{blog.image}}</td>
			<td><img src="{% if blog.image %}{{blog.image.url}}{% endif %}" width="100"></td>
			<td>{{blog.author}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

{% endblock %}

templates/adminhome.html
{% extends 'base.html' %}

{% block content %}
 	<h4>This is protected Page </h4>

 {% endblock %}


 

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	{% if request.user.is_authenticated %}
	<p>logged in as:<span class = "text-info">{{ request.user}}</span> </p>
	<a href="/signout/">SignOut</a>
	{% else %}
	<a href="/signin/">SignIn</a>
	<a href="/signup/">SignUp</a>
	{% endif %}
	<hr>
	{% block content %}
	{% endblock %}
</body>
</html>

templates/blogcomment.html
{% extends "base.html" %}


{% block content %}

<div class = "row">
	<div class = "cd-md-4 mx-auto">
		<h4> Add new comment</h4>
		<form method = "POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form.as_p }} 
			<button class = "btn btn-info btn-block ">Post</button>
		</form>
		
	</div>

	
</div>

{% endblock %}

templates/blogdetail.html
{% extends "base.html" %}


{% block content %}


{% if blogobject.image %}
<img src="{{blogobject.image.url}}" width="500">
{% else %}

<h4>No image</h4>
{% endif %}

<h4> Title: <small>{{blogobject.title}}</small></h4>
<p><b>Content:</b>{{blogobject.content}}</p>
<p><b>Author:</b>{{blogobject.author}}</p>

<h4> All Commments</h4>
{% for comment in blogobject.comment_set.all %}

<li>{{comment.commentor}} says:{{comment.comment}} {{comment.created_at|timesince}}</li>

{% endfor %}

<h4> Add new comment</h4>
<form method = "POST" action = "{% url 'umapp:blogcomment' blogobject.pk %}" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }} 
	<button class = "btn btn-info btn-block ">Post</button>
</form>



{% endblock %}

templates/error.html
{% extends 'base.html' %}

{% block content %}
 	<h4>Error : {{error}}</h4>

 {% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
 	<h4> Welcome To Home Page </h4>

 {% endblock %}


 

templates/passwordchange.html
{% extends 'base.html' %}

{% block content %}
 	<h4>Change your Password</h4>
 	{% if error %}
 	<li class = "text-danger"> {{error}} </li>
 	{% endif %}
 	<form method = "POST">
 		{% csrf_token %}
 		{{ form.as_p }}
 		<button>Click Here to Change </button>
 	</form>


 {% endblock %}

templates/signin.html
{% extends 'base.html' %}

{% block content %}
 	<h4>SignIn Here</h4>
 	{% if error %}
 	<li class = "text-danger"> {{error}} </li>
 	{% endif %}
 	<form method = "POST">
 		{% csrf_token %}
 		{{ form.as_p }}
 		<button>Sign Up</button>
 	</form>


 {% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
 	<h4>Signup Here</h4>
 	<form method = "POST">
 		{% csrf_token %}
 		{{ form.as_p }}
 		<button>Sign Up</button>
 	</form>

 {% endblock %}